name: Github Actions
on: 
    push:
        branches-ignore:
          - 'no-ga/'
    pull_request:
        branches-ignore:
          - 'no-ga/'
    
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: check-repository
        run: 
      - name: 
        run: date

