name: Github Actions
on: [push, pull_request]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run only on main branch
      if: github.ref == 'refs/heads/main'
      run: echo "this should run only on main"

