name: Github Actions
on: [push, pull_request]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run only on main
        if: github.ref == 'refs/heads/no-ga'
        run: echo "cette branche ne doit pas être utilisée"
             exit 1

